AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 130
  Exclude:
    - 'test/**/*'
  AllowedPatterns: ['^\s*#.*', '.*<<~SQL.*']

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 32
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 350
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - '.simplecov'
    - 'test/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - 'test/**/*'

Lint/ShadowedArgument:
  Exclude:
    - 'test/**/*'